### ISSUE TITLE
Speaker call microphone issues

### ISSUE THREAD

**Issue by iusmac** [Wave-Project/device_xiaomi_rolex#2]
Hi!
I'm using WaveOS for Xiaomi 4A. Before I used the stock MiUI 10. When I migrated to it, during a call the people starts complaining constantly when I enable the speaker. The barely hear me. It seems that the speaker mode during a call drops down the volume of the microphone. In most of the cases it's caused by missing audio-related values (such as _persist.audio.fluence*_) in _build.prop_. Can you try to fix this?
Thanks.

**Comment by Thagoo** [comment]
It will be helpful if you provide a logcat by logging this bug

**Comment by iusmac** [comment]
@Thagoo I made a call using speaker from _04-09 14:42_ to _04-09 14:50_ approximately
[logcat.log](https://github.com/Wave-Project/device_xiaomi_rolex/files/6285802/logcat.log)
Thank you.

**Comment by Thagoo** [comment]
This is issue is not seen in the latest test so lets wait for the next update 👍
